name: Branch Build

on:
  pull_request:
  push:
    branches:
      - master
      - release-*

env:
  NODE_VERSION: 12.16.0

jobs:
  build:
    if: startsWith(github.repository, 'spinnaker/')
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION  }}

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: yarn --frozen-lockfile

      - name: Eslint Plugin Build
        run: |
          cd packages/eslint-plugin
          yarn tsc
          yarn test

      - name: Assert - no lint violations
        run: yarn lint

      - name: Assert - code is formatted
        run: yarn prettier:check

      - name: Build Modules
        run: yarn modules

      - name: Unit Tests
        run: yarn test --single-run

      - name: Functional Tests
        run: yarn functional

      - name: Yarn Build
        run: yarn build
