name: PR Build

on: [ pull_request ]

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Xmx2g -Xms2g
  CONTAINER_REGISTRY: us-docker.pkg.dev/spinnaker-community/docker
  NODE_VERSION: 12.16.0

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION  }}
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install Dependencies
        run: yarn --frozen-lockfile
      - name: Eslint Plugin Build`
        run: |
          cd packages/eslint-plugin
          yarn tsc
          yarn test
      - name: Assert - no lint violations
        run: yarn lint
      - name: Assert - code is formatted
        run: yarn prettier:check
      # unit & functional tests run as part of gradle
      - name: Unit Tests
        run: yarn test --single-run

      - name: Functional Tests
        run: yarn functional

      - name: Yarn Build
        run: yarn build



  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'zulu'
        cache: 'gradle'
    - name: Extract repository name
      id: extract_repo_name
      run: echo ::set-output name=REPO::${GITHUB_REPOSITORY##*/}
    - name: Build
      run: ./gradlew build
    - name: Get date
      id: get_date
      run: echo ::set-output name=DATETIME::$(date --utc +'%Y%m%d%H%M')
    - name: Build slim container image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile.slim
        tags: |
          "${{ env.CONTAINER_REGISTRY }}/${{ steps.extract_repo_name.outputs.REPO }}:latest"
          "${{ env.CONTAINER_REGISTRY }}/${{ steps.extract_repo_name.outputs.REPO }}:${{ github.sha }}-${{ steps.get_date.outputs.DATETIME }}"
          "${{ env.CONTAINER_REGISTRY }}/${{ steps.extract_repo_name.outputs.REPO }}:latest-slim"
          "${{ env.CONTAINER_REGISTRY }}/${{ steps.extract_repo_name.outputs.REPO }}:${{ github.sha }}-${{ steps.get_date.outputs.DATETIME }}-slim"
    - name: Build ubuntu container image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile.ubuntu
        tags: |
          "${{ env.CONTAINER_REGISTRY }}/${{ steps.extract_repo_name.outputs.REPO }}:latest-ubuntu"
          "${{ env.CONTAINER_REGISTRY }}/${{ steps.extract_repo_name.outputs.REPO }}:${{ github.sha }}-${{ steps.get_date.outputs.DATETIME }}-ubuntu"
